### ISSUE TITLE
cmd is not a function

### ISSUE THREAD

**Issue by eden-omb** [medusajs/admin#197]
The CLI seems to be broken. I followed the instructions listed (here)[https://github.com/medusajs/admin#-setting-up-admin] and got the following output:

```
$ medusa user -e my@email.com -p password --verbose
medusa user

Create a user

Options:
  --verbose                Turn on verbose output                                                           [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                     [boolean] [default: false]
  --json                   Turn on the JSON logger                                                          [boolean] [default: false]
  -e, --email              User's email.                                                                                      [string]
  -p, --password           User's password.                                                                                   [string]
  -i, --id                 User's id.                                                                                         [string]
  -h, --help               Show help                                                                                         [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project                  [boolean]
medusa user

Create a user

Options:
  --verbose                Turn on verbose output                                                           [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                     [boolean] [default: false]
  --json                   Turn on the JSON logger                                                          [boolean] [default: false]
  -e, --email              User's email.                                                                                      [string]
  -p, --password           User's password.                                                                                   [string]
  -i, --id                 User's id.                                                                                         [string]
  -h, --help               Show help                                                                                         [boolean]
  -v, --version            Show the version of the Medusa CLI and the Medusa package in the current project                  [boolean]
TypeError: cmd is not a function
    at /home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:309:7
    at /home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/home/eden/.nvm/versions/node/v16.13.0/lib/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

```

**Comment by olivermrbl** [comment]
This often happens because you are running the command within a directory, that does not hold a Medusa project. Can you check, if this is the case for you? :)

**Comment by olivermrbl** [comment]
Closed due to inactivity :) Feel free to open up again @eden-omb
