### ISSUE TITLE
Can't re-add region that was deleted 

### ISSUE THREAD

**Issue by jzatarain** [medusajs/admin#371]
I had the 2 default regions + Mexico, that I added.
I deleted every region, and tried to add Mexico again, but I got this error:
![image](https://user-images.githubusercontent.com/20093580/154058488-b907c9fe-bcdd-4e5e-ac33-0cfe0c04887d.png)

**Comment by jzatarain** [comment]
Error: MEXICO already exists in MEXICO, delete it in that region before adding it
    at RegionService.<anonymous> (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\region.js:439:35)
    at step (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\region.js:48:23)
    at Object.next (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\region.js:29:53)
    at fulfilled (C:\dev\my-medusa-store\node_modules\@medusajs\medusa\dist\services\region.js:20:58) {
  type: 'duplicate_error',
  code: undefined,
  date: 2022-02-15T11:35:52.064Z

**Comment by olivermrbl** [comment]
Solved in [PR to core](https://github.com/medusajs/medusa/pull/1330)
