### ISSUE TITLE
Not able to create a new user

### ISSUE THREAD

**Issue by minstn** [medusajs/admin#687]
After executing `medusa user --verbose -e some@email.com -p mypassword1234` i get the following error:

```
medusa user --verbose -e some@email.com -p mypassword1234
medusa user

Create a user

Options:
  --verbose                Turn on verbose output                                                                                          [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                                                    [boolean] [default: false]
  --json                   Turn on the JSON logger                                                                                         [boolean] [default: false]
  -e, --email              User's email.                                                                                                                     [string]
  -p, --password           User's password.                                                                                                                  [string]
  -i, --id                 User's id.                                                                                                                        [string]
  -h, --help               Show help                                                                                                                        [boolean]
  -v, --version            Show version number                                                                                                              [boolean]
TypeError: cmd is not a function
    at /Users/user1/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:309:7
    at /Users/user1/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:108:24
    at Object.handler (/Users/user1/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:54:24)
    at Object.runCommand (/Users/minstn/.config/yarn/global/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/minstn/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/Users/minstn/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:584:29)
    at module.exports (/Users/minstn/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/create-cli.js:392:6)
    at Object.<anonymous> (/Users/minstn/.config/yarn/global/node_modules/@medusajs/medusa-cli/dist/index.js:70:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

Conditions:
* Medusa cli is install globally
* Node version `v16.15.0`
* Medusa `"@medusajs/medusa": "^1.3.4"`

**Comment by kasperkristensen** [comment]
@minstn Are you running the command from your server directory? 

And this would be more relevant in the core repo https://github.com/medusajs/medusa for future reference.

**Comment by minstn** [comment]
@kasperkristensen This was executed on my local development machine, in the `medusajs/admin` project directory, hence i filed this report here. are you sure this is related to [medusajs/medusa](https://github.com/medusajs/medusa) and not [medusajs/admin](https://github.com/medusajs/admin)? 

I installed medusa command line tools globally with `npm install -g @medusajs/medusa-cli@1.3.3`, maybe that is the problem?

**Comment by kasperkristensen** [comment]
@minstn You need to run the command from your server directory, and not the admin directory. The admin is just a frontend wrapping around our admin API. The `medusa user` command writes a new user to your database, which is why you need to run the command from the server directory 😄

**Comment by minstn** [comment]
solved! thanks @kasperkristensen !
