### ISSUE TITLE
cannot start on ubuntu server

### ISSUE THREAD

**Issue by AhmadrezaBanitaba** [medusajs/admin#823]
Hello

After cloning the repository, installing the node modules, I get this error when trying to start the server.
```
> medusa-admin@0.1.0 start
> npm run dev


> medusa-admin@0.1.0 dev
> vite --port 7000

file:///home/ubuntu/medusa-admin/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by kasperkristensen** [comment]
Hi @AhmadrezaBanitaba, could be an issue of you having an older version of Node installed that is not compatible with Vite. You can do `node -v` to check your current version and ensure that is compatible with Vite per the requirements described here: https://vitejs.dev/guide/#scaffolding-your-first-vite-project.
