### ISSUE TITLE
Medusa-react miss package `useAdminCreateStockLocation`

### ISSUE THREAD

**Issue by quang-ng** [medusajs/admin#915]
Hi all, 

I’m deploying admin page in production, I run `yarn run build` but it gets an error like this. I’m using `"medusa-react": "^4.0.3"` as in the repository `package.json` file. Am I using the correct version of `medusa-react” or missing anything? I include my dockerfile. Please help!!!

My Dockerfile
```
FROM node:16-alpine as build
WORKDIR /usr/app
COPY . /usr/app
RUN yarn install --frozen-lockfile
RUN yarn run build

FROM nginx:1.23.1-alpine
EXPOSE 80
COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/dist /usr/share/nginx/html
```

The log trace
```
> medusa-admin@0.1.0 build
> vite build

vite v4.1.4 building for production...
✓ 2396 modules transformed.
"useAdminCreateStockLocation" is not exported by "node_modules/medusa-react/dist/index.mjs", imported by "src/domain/inventory/locations/new/index.tsx".
file: /home/quang/heniken_projects/AdminDashboard/src/domain/inventory/locations/new/index.tsx:9:2
 7: import {
 8:   useAdminAddLocationToSalesChannel,
 9:   useAdminCreateStockLocation,
      ^
10: } from "medusa-react"
11: import { useForm } from "react-hook-form"
error during build:
RollupError: "useAdminCreateStockLocation" is not exported by "node_modules/medusa-react/dist/index.mjs", imported by "src/domain/inventory/locations/new/index.tsx".
    at error (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:2095:30)
    at Module.error (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:13143:16)
    at Module.traceVariable (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:13528:29)
    at ModuleScope.findVariable (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:12007:39)
    at ReturnValueScope.findVariable (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at ChildScope.findVariable (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at Identifier.bind (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:7921:40)
    at CallExpression.bind (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:5716:23)
    at CallExpression.bind (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:9458:15)
    at VariableDeclarator.bind (file:///home/quang/heniken_projects/AdminDashboard/node_modules/rollup/dist/es/shared/node-entry.js:5716:23)
```

**Comment by HarveyNgo** [comment]
I also face this issue, any suggestion

**Comment by olivermrbl** [comment]
@quang-ng What version of Medusa Admin are you using? To me, it looks like you are working with changes currently on `develop`, which is not stable for production environments yet. 

If this is intentional, you similarly need to install the `next` version of the core and related packages, as you would otherwise not have the inventory + stock location hooks from `medusa-react`.

**Comment by Gunkev** [comment]
I equally cloned the Medusa admin recently and when I run it, I am getting this interface on localhost:7000. 
![ui error](https://github.com/medusajs/admin/assets/36812576/82e63191-ec68-4d5b-873f-b3c9e0fd225b)
